/*
 * Generated by src/saveVersion.sh
 */
@HadoopVersionAnnotation(version="2.0.3-alpha", revision="1443299", branch="branches/branch-2.0.3-alpha/hadoop-common-project/hadoop-common",
                         user="hortonmu", date="Thu Feb  7 03:33:31 UTC 2013", url="https://svn.apache.org/repos/asf/hadoop/common/branches/branch-2.0.3-alpha/hadoop-common-project/hadoop-common",
                         srcChecksum="30d3d872f9f4a8d4c53d8cfaa17393f4")
package org.apache.hadoop;
