/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_io_nativeio_NativeIO_CachedName */

#ifndef _Included_org_apache_hadoop_io_nativeio_NativeIO_CachedName
#define _Included_org_apache_hadoop_io_nativeio_NativeIO_CachedName
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
